### ISSUE TITLE
I can't draw the rest of the owl

### ISSUE THREAD

**Issue by HunterZ** [DaanDeMeyer/reproc#100]
I'm giving up on trying to use this because the documentation is just too lean. It's not sufficient to say "look at the examples" when the examples don't even show all of the API being meaningfully used.

I mostly just want to know what actual return values can be returned by each function, and how to actually interpret them. For example, the documentation mentions that `reproc_wait()` / `reproc::process::wait()` can be used with a timeout of zero to check whether the process has exited - but how exactly?

I basically had to waste an entire day studying the C API and then the C++ extensions to understand this library at all, and except for capturing the output, I still don't know enough to do more than what `std::system()` could handle.

**Comment by DaanDeMeyer** [comment]
I'm happy to take PRs improving the documentation. I don't have a need for reproc myself anymore so I don't have any motivation to write more documentation for it.

**Comment by HunterZ** [comment]
Thanks. I ended up having more success with `tiny-process-library` so I'll close this.
