### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [DaanDeMeyer/reproc#11]
Would you like to [replace any double quotes](https://github.com/DaanDeMeyer/reproc/blob/9615ef67b934941b6551a442a477ab92f1f34dc7/include/reproc/reproc.h#L6 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by DaanDeMeyer** [comment]
Can't believe I missed that. Should be fixed by 17d0c7efb9da286b71fb884a9081be0ecaf0e776. Thanks for reporting the issue!

**Comment by elfring** [comment]
Thanks for [your small source code adjustment](https://github.com/DaanDeMeyer/reproc/commit/17d0c7efb9da286b71fb884a9081be0ecaf0e776 "Use angle brackets where appropriate").
