### ISSUE TITLE
is it possible to provide a amalgamation version?

### ISSUE THREAD

**Issue by etorth** [DaanDeMeyer/reproc#12]
I mean merge all headers into one like reproc.h, and all .c to a big reproc.c

This is an excellent lib and we use it easily to mimic the io device like QProcess in Qt.
I believe user would like to embed it in their own repos to simplify their interface/script/building env.

Or maybe the cmake object library can do the same thing.
Can we have an option to support this?

Thanks for it,
Anhong

**Comment by DaanDeMeyer** [comment]
I'd like to avoid moving all code into a single file. An possible solution would be to write a script that concatenate all source files into a combined version. However, I'm not sure if this is the best approach. Ideally, we'd be able to integrate reproc into your build system.

I'd also be willing to answer questions related to writing build files to integrate reproc into a build system other than CMake. If the build system is moderately popular, it might even be possible to put those build files into the reproc repository alongside the CMake build. If not, you can host your own fork of reproc with along with the added build files.

**Comment by DaanDeMeyer** [comment]
Closing the issue since I'd prefer making reproc easy to consume without concatenating the source files.
