### ISSUE TITLE
reproc.c boolean type issue with Visual Studio

### ISSUE THREAD

**Issue by scottmudge** [DaanDeMeyer/reproc#14]
When compiling with Visual Studio 2015, the following error was encountered with reproc.c:

`reproc.c(42): error C2065: 'false': undeclared identifier`

as the boolean type is not valid for the C compiler.

This has been corrected by adding: 

```
#ifdef _MSC_VER
#ifndef false
#define false 0
#endif
#endif
```
Right after the include block in reproc.c

**Comment by DaanDeMeyer** [comment]
It's strange that the error doesn't happen on Appveyor which also builds against Visual Studio 2015. `reproc.h` also includes `stdbool.h` which should result in `false` being declared.

Can you post the build commands you executed? I'd prefer to find the root of the problem before making a fix.

**Comment by DaanDeMeyer** [comment]
Closing the issue due to lack of response and no problems being apparent from the CI Visual Studio 2015 builds.
