### ISSUE TITLE
Compilation error in the process_create() if the ATTRIBUTE_LIST_FOUND is not defined

### ISSUE THREAD

**Issue by KVic** [DaanDeMeyer/reproc#15]
https://github.com/DaanDeMeyer/reproc/blob/d50c91b68a3a54d69b97a4f3c2ba496f5963203a/reproc/src/windows/process.c#L103

It looks like this branch of `#if defined(ATTRIBUTE_LIST_FOUND)` was not updated when the `options` parameter was added. Therefore, a compilation error occurs if the `ATTRIBUTE_LIST_FOUND` is not defined.

**Comment by DaanDeMeyer** [comment]
Thanks for reporting the issue! I've pushed a commit that should fix the issue. I'll probably release 5.0.0 soon with the fix included
