### ISSUE TITLE
last commit seem's conflicting:

### ISSUE THREAD

**Issue by Milerius** [DaanDeMeyer/reproc#27]
```
/reproc.dir/src/windows/pipe.c.obj   -c _deps/reproc-src/reproc/src/windows/pipe.c
_deps/reproc-src/reproc/src/windows/pipe.c:178:14: error: conflicting types for 'pipe_wait'
REPROC_ERROR pipe_wait(HANDLE *ready, HANDLE out, HANDLE err)
             ^
_deps/reproc-src/reproc/src\pipe.h:51:1: note: previous declaration is here
pipe_wait(const reproc_handle *pipes,
```

Is it possible to have a `dev` branch or a second branch ?

Because i'm between a release that i'm waiting and there is only `master` branch

So basically it's break my CI when there is a breaking change :/

**Comment by DaanDeMeyer** [comment]
Is it an option to use CMake FetchContent's git support for reproc? That way you can checkout a specific commit instead of having to follow the master branch.

For example, to get (and stick to) the current latest commit on the master branch:

```cmake
FetchContent_Declare(
  reproc
  GIT_REPOSITORY https://github.com/DaanDeMeyer/reproc.git
  GIT_TAG 8322f0b94c1a5baf72117597b9a86162a502fb3b
)
```

**Comment by Milerius** [comment]
Ah yes I can normally use a specific commit to solve this problem I didn't think about that
