### ISSUE TITLE
include reproc to other libs

### ISSUE THREAD

**Issue by etorth** [DaanDeMeyer/reproc#28]
Thanks for this excellent project!
I have a software requirement that trying to do pimpl using reproc but no idea how to integrate.

Basically what I need is to have a base ```class comm_interface```. then I have many derived classes, like ```asio_comm_interface```, it connects to a running server and communicates via socket, I also want to provide a ```reproc_comm_interface```, then the user can spawn a process locally and communicate with it by read/write stdio.

Because we design it in PIMPL way, the lib user shouldn't know anything about reproc, or asio, they just do
```cpp
auto p = new reproc_comm_interface(/*args*/);
```
then use interfaces defined in ```common_interface``` to do read/write.
we plan to only provides a header libnvc.hpp and a libnvc.a
But currently no matter how, I have to build the libreproc.a and ship to the user, use have to link to both.

Is there any way we can do to collect all symbols just in libnvc.a, not an extra libreproc.a?
asio doesn't have this issue since it's header only.
we also depend on mpack, it provides a single file to include all and we can build with it, then it's ok.

Thanks,
etorth

**Comment by DaanDeMeyer** [comment]
There are ways to combine static libraries.

Windows: 

https://stackoverflow.com/questions/13492365/how-to-merge-two-windows-vc-static-library-into-one

POSIX:

https://stackoverflow.com/questions/8170450/combine-static-libraries

If your build system supports including other projects of the same build system I'm not completely oposed to maintaining a stripped down build script of that build system aside from the usual CMake build to allow including reproc as a subproject in that build system.

**Comment by DaanDeMeyer** [comment]
I see that libnvc uses CMake as well. One other thing that could work is me adding an option to build reproc and reproc++ as object libraries. You can the include reproc with `add_subdirectory` and include the object files in your library as follows:

`add_library(libnvc $<TARGET_OBJECTS:reproc> $<TARGET_OBJECTS:reproc++>)`

I was planning on adding this but waiting until CMake hopefully makes object libraries work transitively by just doing `target_link_libraries`. However, if this solves your problem I can add the option immediately.

**Comment by DaanDeMeyer** [comment]
Actually, I can do `target_sources(reproc++ INTERFACE $<TARGET_OBJECTS>:reproc>)` in reproc's CMake file which makes `target_link_libraries(libnvcc PRIVATE reproc++)` just work.

**Comment by DaanDeMeyer** [comment]
The latest commit on master adds `REPROC_OBJECT_LIBRARIES` to build reproc and reproc++ as CMake object libraries.

The following can now be used to directly bundle reproc into a library when using CMake:

```cmake
include(FetchContent)

FetchContent_Declare(
  reproc
  GIT_REPOSITORY https://github.com/DaanDeMeyer/reproc.git
  GIT_TAG 0a2865af200bb1bc5bb7f5140383c3f51ebc6d13
)

set(REPROC++ ON)
set(REPROC_OBJECT_LIBRARIES ON)

FetchContent_MakeAvailable(reproc)

target_link_libraries(libnvc PRIVATE reproc++)
```

**Comment by etorth** [comment]
Thanks so much for your help!
I have integrated your package to the libnvc and it just works!

Best,
Etorth
