### ISSUE TITLE
Will be a release?

### ISSUE THREAD

**Issue by jetm** [DaanDeMeyer/reproc#3]
Thank you for reproc project.

I wonder if in some time will be a release? With a release version will be easier for the Linux distributions to make a package.

**Comment by DaanDeMeyer** [comment]
I'd prefer to wait until reproc's been used a little more. I still need to do a bigger project with it myself to make sure there are no obvious bugs anymore and that the API design is solid (although it's already used for running short lived processes in [cquery](https://github.com/cquery-project/cquery)).

I know that the Arch User Repository (Arch Linux) has a convention where packages are made with a `-git` suffix that track the master branch of a library/application. The same could be done for reproc. I'm not sure about other distro's.

I'll do an alpha release but I don't think it's a good idea to start making Linux packages off that.

**Comment by jetm** [comment]
@DaanDeMeyer Thank you. I will wait for a stable version or formal release to make a package in AUR. I always avoid the -git package.

**Comment by DaanDeMeyer** [comment]
@jetm I've just released 1.0.0 if you're still interested in packaging reproc.

**Comment by DaanDeMeyer** [comment]
Sounds great. You can add a section under "Getting Started" in the readme with the install instructions.

**Comment by DaanDeMeyer** [comment]
Fixed by #5
