### ISSUE TITLE
Variable referenced twice

### ISSUE THREAD

**Issue by Milerius** [DaanDeMeyer/reproc#30]
https://github.com/DaanDeMeyer/reproc/blob/00b8616ec935752985cbc53ad0cef42f9f698358/reproc%2B%2B/include/reproc%2B%2B/detail/array.hpp#L27

Hey, any reason why the variable is assigned twice time here ?

**Comment by DaanDeMeyer** [comment]
Nope, that's a bug. Thanks for pointing it out! I'll push a fix immediately.

**Comment by Milerius** [comment]
no problem, you maybe interested to use https://www.viva64.com/en/pvs-studio/

It's free for open source project, since I'm using your library I got the report from your library too @DaanDeMeyer

**Comment by DaanDeMeyer** [comment]
That's pretty nifty, I'll look into setting up some more static analyzers for reproc including PVS. Of course, you're welcome to keep reporting these things if PVS finds any more. 

(I hope the latest changes didn't impact you too heavily, I did some breaking changes but they should be mostly contained to the C library)

**Comment by Milerius** [comment]
TBH with you I'm stick to a specific commits since a moment @DaanDeMeyer I will upgrade when a new release tag will be ready.

**Comment by Milerius** [comment]
<img width="835" alt="Capture d’écran 2019-12-26 à 23 26 55" src="https://user-images.githubusercontent.com/21139416/71492418-4ee27e00-2837-11ea-88dd-4cbf24a78750.png">


There is this one too but seem's to be a false positive @DaanDeMeyer

**Comment by DaanDeMeyer** [comment]
Ahh, I thought you got the PVS warning because you were following the master branch but the warning was simply from an old version.

The second one is indeed a false positive, although it shouldn't trigger anymore in newer commits as I've completely revised error handling in the C implementation.

**Comment by Milerius** [comment]
Ah yeah that's why, ok I will upgrade once the new tag is release so.

**Comment by DaanDeMeyer** [comment]
I'll try and get the new version out the door ASAP so you can use a stable release again.

**Comment by Milerius** [comment]
very nice. Recently I liked a lot the approach of the API process from the nim programming langage:


https://github.com/nim-lang/Nim/blob/version-1-0/lib/pure/osproc.nim#L66

I liked a lot the API that's look like:

```nim
            mm2Instance = startProcess(command=toolsPath & "/mm2", args=[$$mm2_cfg], env = nil, options={poParentStreams}, workingDir=toolsPath)
```

May be you will find the API/code interesting for inspiring ^^'
