### ISSUE TITLE
Test binary is not generated with -DREPROC_TEST=ON

### ISSUE THREAD

**Issue by jetm** [DaanDeMeyer/reproc#31]
With `reproc v9` I could call `test` binary to run the tests, but with `v10` the `test` binary file is not generated.

**Comment by DaanDeMeyer** [comment]
Testing is now done via `cmake --build build --target test`. I'll make sure to update the documentation and changelog.

**Comment by jetm** [comment]
@DaanDeMeyer thank you for the flash response. I going to update the Arch package too.
