### ISSUE TITLE
Is reproc_write not blocking anymore?

### ISSUE THREAD

**Issue by SylvainCecchetto** [DaanDeMeyer/reproc#34]
Hi and thank you for reproc!

I use reproc for a personal project and today I updated it but my project doesn't work anymore...

This my usage:

*  Start a subprocess (an SMT solver instance that permanently wait for user input on `stdin` and prints result on `stdout`) with `process.start();`
* Write a string on subprocess `stdin`with `process.write(reinterpret_cast<const uint8_t*>(s.data()), static_cast<unsigned int>(s.length()));`
* Read subprocess answer with character by character with:
```c++
uint8_t buf[1];
std::string s = "";
while(true)
{
    std::pair<size_t, std::error_code> bytes_read_and_error = process.read(reproc::stream::out, buf, 1);
    char c = (char)buf[0];
    if(c == '\n') break;
    s += c;
}
```

It works well before the update but now I always get a `Resource temporarily unavailable` on the read.

BUT, if I add a `sleep(5)`after the `write`it works.

Do you know what's the issue?

Thank you!

**Comment by DaanDeMeyer** [comment]
Yes, I finally figured out how to implement polling on all platforms so I changed the read and write functions to be nonblocking. `reproc::poll` can be used to wait until a stream becomes readable/writable.

Example (not tested):

```c++
std::error_code ec;

while (true) {
  std::tie(_, ec) = process.poll(event::out);
  if (ec) {
    // Handle error
  }

  size_t bytes_read = 0;
  std::tie(bytes_read, ec) = process.read(reproc::stream::out, buf, 1);
  if (ec) {
    // Handle error
  }

  ...
}
```

**Comment by SylvainCecchetto** [comment]
I do not understand very well what's the purpose of `process.poll` but it's work very well now!

Thank you very munch for your fast and useful answer!

**Comment by SylvainCecchetto** [comment]
Hum, my issue is partially resolved.
No problem on macOS, but on Debian with the same code I always get a `error: Broken pipe` when I try to read on my subprocess with the code below.

Do I miss something?
