### ISSUE TITLE
Are c++ examples outdated?

### ISSUE THREAD

**Issue by bangusi** [DaanDeMeyer/reproc#35]
Windows,
Visual Studio 2017
I tried to compile run.cpp as is and got lots of errors.
`e.g.  error C2039: 'parent': is not a member of 'reproc::options::<unnamed-type-redirect`
`error C2039: 'deadline': is not a member of 'reproc::options'`

**Comment by DaanDeMeyer** [comment]
Can you share which version of reprocxx you're using? I have a suspicion it might be out-of-date. The examples in the repository apply to the latest released version and there have been breaking changes in the latest releases.

**Comment by bangusi** [comment]
Ver  10.0.3 installed from vcpkg

**Comment by DaanDeMeyer** [comment]
The `run` function was added in v11.0.0. You'll have to update to that release in order to use it.
