### ISSUE TITLE
API for child process ID

### ISSUE THREAD

**Issue by mvphilip** [DaanDeMeyer/reproc#43]
Hello Daan, Great library. Thank you very much for releasing.

Can you accept a pull request for child PID ? Ive exposed the process->handle on both c and c++ side 
through reproc_childPid and childPid methods respectively. I am using the childPids for accounting purposes and
so I needed the API.

Thanks,

-mp

**Comment by DaanDeMeyer** [comment]
Sounds great! Maybe call the methods `reproc_pid` and pid` respectively for C and C++.
