### ISSUE TITLE
error: expected '}'

### ISSUE THREAD

**Issue by yurivict** [DaanDeMeyer/reproc#46]
I tried the example from README, but it turns out that there is an unclosed brace in the installed header:
```
$ cc -o proc proc.cpp `pkg-config --cflags --libs reproc++`
proc.cpp:8:2: error: expected '}'
}
 ^
/usr/local/include/reproc/drain.h:6:12: note: to match this '{'
extern "C" {
           ^
1 error generated.
```

reproc-14.1.0
FreeBSD 12.2
clang-10

**Comment by yurivict** [comment]
Apparently, it is broken as a C++ code, but works ad a C code. The C++ ifdef in the header is broken.

**Comment by DaanDeMeyer** [comment]
That's pretty embarassing, let me quickly fix that and put out a new release.

**Comment by DaanDeMeyer** [comment]
Released a new version with the fix. Thanks for reporting!
