### ISSUE TITLE
Multi wide character error

### ISSUE THREAD

**Issue by Milerius** [DaanDeMeyer/reproc#48]
Hello i have the following error when i try to launch a process:

```
command line: [C:\Users\Public\Documents\atomicDEX-Desktop\cmake-build-debug\bin\assets\tools/mm2/mm2], from directory: [C:\Use
rs\Public\Documents\atomicDEX-Desktop\cmake-build-debug\bin\assets\tools/mm2/]

error when spawning process No mapping for the Unicode character exists in the target multi-byte code page
```

```cpp
        options.working_directory = strdup(tools_path.string().c_str());

        SPDLOG_DEBUG("command line: [{}], from directory: [{}]", args[0], options.working_directory);
        const auto ec = m_mm2_instance.start(args, options);
        std::free((void*)options.working_directory);
        if (ec)
        {
            SPDLOG_ERROR("error when spawning process {}", ec.message());
            std::exit(EXIT_FAILURE);
        }
```

**Comment by Milerius** [comment]
![image](https://user-images.githubusercontent.com/21139416/102020385-32599180-3d79-11eb-8ee6-817a744decb8.png)

I'm using https://en.cppreference.com/w/cpp/filesystem/temp_directory_path which seems for this specific users to returns a string like: `"MM_CONF_PATH=C:\\Users\\YUSUFK~1\\AppData\\Local\\Temp\\MM2.json"`

Trying to extend the env with this value but produce 1113 windows error code

**Comment by Milerius** [comment]
To reproduce you can create a windows user named: `Yusuf KOÇ` and try to extend the env with `std::filesystem::temp_directory_path() / "file.json"`

You will never be able to start a process.

**Comment by DaanDeMeyer** [comment]
Unfortunately, I don't have a windows system at hand anymore. From looking at `MM_CONF_PATH`, it seems either the '~' or the double '\\' could be causing the issue.

Could you try modifying the path a bit to try and figure out exactly which character sequence is causing the error?

**Comment by Milerius** [comment]
> Unfortunately, I don't have a windows system at hand anymore. From looking at `MM_CONF_PATH`, it seems either the '~1' or the double '\' could be causing the issue.
> 
> Could you try modifying the path a bit to try and figure out exactly which character sequence is causing the error?

Obviously the char: `Ç` is causing the error, but this is well handled by microsoft atm

**Comment by DaanDeMeyer** [comment]
Can you try using the `u8string()` method to convert a path to a string? reproc expects UTF-8 encoded strings as input. I think using `string()` on Windows gives back UTF-16 strings.

**Comment by Milerius** [comment]
I confirm if i manually enter in the windows explorer: `C:\Users\YUSUFK~1` it expands to `C:\Users\Yusuf KOÇ`

So it's should be a known syntax btw : https://stresstest.atomicdex.io/ more than 800 users are testing our app right now and using reproc :p 

Will test the above solution

**Comment by Milerius** [comment]
> Can you try using the `u8string()` method to convert a path to a string? reproc expects UTF-8 encoded strings as input. I think using `string()` on Windows gives back UTF-16 strings.

Even using `u8string()` produce the same result, logs:

```
command
 line: C:\Users\Public\Documents\atomicDEX-Desktop\cmake-build-debug\bin\assets\tools/mm2/mm2, from directory: C:\Users\
Public\Documents\atomicDEX-Desktop\cmake-build-debug\bin\assets\tools/mm2/ conf_path: C:\Users\YUSUFK~1\AppData\Local\Te
mp\MM2.json
```

**Comment by DaanDeMeyer** [comment]
So if you pass `K~1` to reproc as environment value, you get the same error?

**Comment by Milerius** [comment]
> So if you pass `u8"K~1"` to reproc as environment value, you get the same error? Also, what happens if you pass `u8"KOÇ"` instead?

`u8"YUSUFK~1"` -> `No mapp
ing for the Unicode character exists in the target multi-byte code page.`

`u8"Yusuf KOÇ"` -> `No mapp
ing for the Unicode character exists in the target multi-byte code page.`

**Comment by DaanDeMeyer** [comment]
Can you post the strings returned by `u8string` and `generic_u8string`? I'm curious what the exact difference is there. This might be something to add to reproc's documentation.

**Comment by Milerius** [comment]
> Can you post the strings returned by `u8string` and `generic_u8string`? I'm curious what the exact difference is there. This might be something to add to reproc's documentation.

only `\\\` become `/`

**Comment by DaanDeMeyer** [comment]
UTF conversion and paths are defintely not as well tested as they should be. Feel free to post a PR that adds some of these cases as new UTF-8 and path tests if you have time. That makes sure this keeps working as expected.

**Comment by Milerius** [comment]
> UTF conversion and paths are defintely not as well tested as they should be. Feel free to post a PR that adds some of these cases as new UTF-8 and path tests if you have time. That makes sure this keeps working as expected.

Sure !  thanks a lot for your help man
