### ISSUE TITLE
Redirect child process stdout to parent?

### ISSUE THREAD

**Issue by cmaughan** [DaanDeMeyer/reproc#50]
If I set this option, I can make a child output to a file path instead of the console:
options.redirect.out.path = "c:/foo/bar.txt"

How would I make the child process output to the same stdout as the parent (so the output appears in the console of the parent process)?  Is that possible?

**Comment by DaanDeMeyer** [comment]
`options.redirect.out.type = reproc::redirect::parent;` ?

**Comment by DaanDeMeyer** [comment]
Closing, feel free to reopen if the above doesn't work as expected.

**Comment by cmaughan** [comment]
Ah, that was the magic I was missing, thanks!
