### ISSUE TITLE
integration with libevent

### ISSUE THREAD

**Issue by thefallentree** [DaanDeMeyer/reproc#55]
Hi, is there a example of integrating reproc with event lib like libevent? It looks like the example included is by launching a new thread -- which is fine, but I have a program that already using libevent and want to see what's the best model

**Comment by DaanDeMeyer** [comment]
So I haven't actually tried this, but I'd assume the best model would be to just move ownership of the stdout/stdin/stderr and exit file descriptors out of reproc. e.g. we could add a new function reproc_release which would take a stream and return the handle associated with that stream. That handle can then be used as you want with libevent and reproc will act like it doesn't exist anymore. You probably wouldn't want to use any of reproc's I/O functions then but just handle all of that with libevent. You could still use reproc_terminate and reproc_kill to send signals and when the exit pipe is closed, you'd have to call reproc_destroy.

We don't expose everything that's needed for this today unfortunately. We'd need a new function to move the file descriptors out of reproc and probably a new stream REPROC_STREAM_EXIT so you can get the exit pipe file descriptor out as well. You'd then register those 4 descriptors with libevent.

Unfortunately, no ready made examples for this are available though. I'd happily review a PR that adds the required functionality or an example of how to make this work.

**Comment by DaanDeMeyer** [comment]
Let's close this as the question was answered
