### ISSUE TITLE
Windows command prompt still visible

### ISSUE THREAD

**Issue by Alzathar** [DaanDeMeyer/reproc#6]
reproc version: v2.0.0-beta.3
reproc language: C
IDE: MSVC 2017 x64
OS: Windows 10 x64

----

**Issue**
When executing a program with the command `reproc_start`, I still see a command prompt opening and closing.

**Expected result**
The executed program through `reproc` should be completely invisible.

**Possible fix**
The addition of the flag [`CREATE_NO_WINDOW`](https://docs.microsoft.com/en-us/windows/desktop/ProcThread/process-creation-flags) in the variable `creation_flags `fixes the problem. From the Window Dev Center documentation:

> CREATE_NO_WINDOW : The process is a console application that is being run without a console window. Therefore, the console handle for the application is not set.
This flag is ignored if the application is not a console application, or if it is used with either CREATE_NEW_CONSOLE or DETACHED_PROCESS.

The line [`reproc/src/reproc/windows/process.c:63`](https://github.com/DaanDeMeyer/reproc/blob/master/src/reproc/windows/process.c#L63) should be replaced by:

```c
DWORD creation_flags = CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW;
```

**Comment by Tarquiscani** [comment]
I'm leaving this comment just to help other people that may experience the same issue, not to suggest a change.

The issue appears when starting an Unreal Engine process by this library. 
Normally when you run `UE4Editor.exe -log`, both a game window and a debug console open. The debug console is a child of the Unreal process.
On Windows when starting the process by `reproc` the debug console doesn't show up (despite I can see its process running). Also its output isn't redirected to the parent console. I don't know exactly why this is the case, however I solved by reverting the commit c90924e and changing the following line in `process.windows.c`:

    .wShowWindow = SW_HIDE

with this one:

    .wShowWindow = SW_SHOWNORMAL

Doing so the debug console of Unreal appears in a separate window as expected
